task:
  arm_container:
    image: node:lts #

  node_modules_cache: #
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci --ignore-scripts

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest

  matrix: #
    - name: Build
      build_script: npm run build:ci --all
      binaries_artifacts:
        path: "build/*"
    # - name: Publish
    #   depends_on:
    #     - Build
    #   # only_if: $BRANCH == "master" #
    #   publish_script:
