name: 'create-tagged-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: 'Create Tagged Release'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          draft: true
          files: |
            prebuilds/*.tar.gz
            prebuilds/*.zip
