name: Build iohook

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Windows Prebuilds
          path: prebuilds

  build-mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: macOS Prebuilds
          path: prebuilds

  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install gcc-7 g++-7 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
      - name: Install dependencies (Ubuntu)
        run: sudo apt-get install libxtst-dev

      - run: npm ci --ignore-scripts
      - run: npm run build:ci --all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Linux (Ubuntu) Prebuilds
          path: prebuilds
